//Receba 2 números inteiros. Verifique e mostre todos os números primos existentes entre eles.
//REFAZER

import java.util.Scanner;

public class Exerc40 {
    float num1, num2;
    
    //PROGRAMA PRINCIPAL
    public static void main(String[] args){
    
        ProcedureNum();
        
    }
    static void ProcedureNum(){
        
        float num1, num2;
        System.out.println("Inisra um valor supeior a zero:");
        num1 = scan.newFloat();
        
    }
    
}