/*Receba 2 números reais. Calcule e mostre a diferença desses valores.
*/

import javax.swing.JOptionPane;

public class ExercLt01_10 {
    public static void main(String[] args){
        float num1, num2, total;
        
        num1 = Float.parseFloat(JOptionPane.showInputDialog("Insira o primeiro valor: "));
        num2 = Float.parseFloat(JOptionPane.showInputDialog("Insira o segundo valor: "));
       
        total = num1 - num2;
        JOptionPane.showMessageDialog(null, "A diferença entre os valores é de: " + total);
    }
}
