/* Receba 2 ângulos de um triângulo. Calcule e mostre o valor do 3º ângulo.
*/

import java.util.Scanner;

public class ExercLt01_14 {
    public static void main(String[] args){
        Scanner scan = new Scanner(System.in);
        int ang1, ang2, ang3;
        
        System.out.println("Insira o primeiro ângulo do triângulo: ");
        ang1 = scan.nextInt();
        
        System.out.println("Insira o segundo ângulo do triângulo: ");
        ang2 = scan.nextInt();
        
        ang3 = 180 - (ang1 + ang2);
        
        System.out.println("O terceiro ângulo do triângulo é: " + ang3);   
    }
}